### ISSUE TITLE
Wrong information in Readme

### ISSUE THREAD

**Issue by Ragna-30988** [TYPO3GmbH/ext-usercentrics#11]
I integrated your extension in a typo3 system and had to fetch that you have a mistake in your readme.

In _Configure the JS Files to be handled by Usercentrics:_ you use the attribute **dataProcessingService**
which causes an error in the frontend of my page.
```txt
Oops, an error occurred!
No valid identifier given for file, please check TypoScript configuration.

More information regarding this error might be available online.
```
The Reason is, that in your function T3G\AgencyPack\Usercentrics\Hooks\PageRendererPreProcess::isValidIdentifier
you are checking the index **dataServiceProcessor**. This is the reason the exception is thrown.

In your last [commit](https://github.com/TYPO3GmbH/ext-usercentrics/commit/fb4e82135f90d1a84db6ab7e2694fa2eda349e3b#diff-04c6e90faac2675aa89e2176d2eec7d8) you changed the readme.

Did you just forget the class or is it really a mistake in the readme?

**Comment by NeoBlack** [comment]
Not only wrong information, but there are also some more confusing things.
We have to check and get streamlines the options `dataProcessingService` and `dataServiceProcessor`
In ViewHelper, TypoScript and Controller both means the same, but are used with different wording.
I suppose to streamline the usage and deprecate one of the wording/settings and use only once.

**Comment by NeoBlack** [comment]
"Data Processing Services" is the correct woring, so wie should go with `dataProcessingService`
