### ISSUE TITLE
Usercentrics ID not configurable

### ISSUE THREAD

**Issue by h3nn3s** [TYPO3GmbH/ext-usercentrics#19]
# Bug Report
Usercentrics ID not configured, please set plugin.tx_usercentrics.settingsId in your TypoScript configuration

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10.4 LTS (by reading)
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description
The TypoScript option should be `plugin.tx_usercentrics.settingsId` but is `plugin.tx_usercentrics.id`.

## Steps to Reproduce

1. Set the constant 
2. Clear caches and open the frontend.

**Expected behavior:** [What you expected to happen]
Usercentrics integration is working correct, because the Constant is populated to `plugin.tx_usercentrics.settingsId`

**Actual behavior:** [What actually happened]
Error: 
Usercentrics ID not configured, please set plugin.tx_usercentrics.settingsId in your TypoScript configuration

## Versions
9.0.1

**Comment by andreaskienast** [comment]
Thank you for your report.

Can you please elaborate where you see `plugin.tx_usercentrics.id` is used? I just checked the PageRender pre-process hook and the method `isValidId()` seems fine to me: https://github.com/TYPO3GmbH/ext-usercentrics/blob/9.0.1/Classes/Hooks/PageRendererPreProcess.php#L119-L122

Kind regards
Andreas

**Comment by h3nn3s** [comment]
Sorry, please have a look at the static TypoScript: https://github.com/TYPO3GmbH/ext-usercentrics/blob/9.0.1/Configuration/TypoScript/Static/setup.typoscript#L2
